import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en': {
          // --- General ---
          'error': 'Error',
          'success_snack_title': 'Success',
          'success_snack_msg': 'Operation completed successfully!',
          'cancel_btn': 'Cancel',
          'save_btn': 'Save',
          'done_btn': 'Done',

          // --- Wallet & Financial ---
          'wallet_title': 'Wallet',
          'financial_overview': 'Financial overview',
          'total_collected_today': 'Total Collected Today',
          'from_cash_orders': 'From @count cash orders',
          'to_be_deposited': 'To Be Deposited',
          'exceeded_threshold_msg': "You've exceeded the deposit threshold. Please settle your account to continue accepting orders.",
          'limit_label': 'Limit: @limit',
          'remaining_label': '@amount remaining',
          'your_earnings_label': 'Your Earnings (Delivery Fees)',
          'earnings_msg': 'This is your net income from delivery fees. Available for withdrawal anytime.',
          'cash_held_label': 'Cash Held for Settlement',
          'cash_disclaimer': 'This is collected cash from customers - NOT your earnings. Must be settled with the platform.',
          'view_cash_collections': 'View Cash Collections',
          'view_transactions': 'View Transactions',
          'complete_history': 'Complete history',
          'settle_balance': 'Settle Balance',
          'process_deposit': 'Process deposit',
          'settle_now_btn': 'Settle Now • @amount',
          'cash_collection_title': 'Cash Collection',
          'financial_transactions': 'Financial transactions',
          'total_collected': 'Total Collected',
          'pending_settlement': 'Pending Settlement',
          'not_included_earning': 'Not included in your earnings yet',
          'all_filter': 'All',
          'pending_filter': 'Pending',
          'settled_filter': 'Settled',
          'disputed_filter': 'Disputed',
          'order_col': 'ORDER',
          'amount_col': 'AMOUNT',
          'status_col': 'STATUS',
          'settlement_col': 'SETTLEMENT',
          'financial_transactions_title': 'Financial Transactions',
          'complete_history_desc': 'Complete financial history',
          'current_balance': 'Current Balance',
          'available_withdrawal': 'Available for withdrawal',
          'restaurant_held_balance': 'Restaurant Held Balance',
          'security_deposit_msg': 'Security deposit held by restaurants for cash orders. This ensures payment security.',
          'total_earnings': 'Total Earnings',
          'orders_count': '@count Orders',
          'weekly_growth': '+@percent% this week',
          'how_cash_work': 'How Cash Orders Work',
          'understanding_flow': 'Understanding your payment flow',
          'step_1_title': 'Customer Pays Cash',
          'step_1_desc': 'You collect full amount (Order + Delivery fee)',
          'step_2_title': 'Order Value Deducted',
          'step_2_desc': 'Only meal price deducted from restaurant balance',
          'step_3_title': 'You Keep Delivery Fee',
          'step_3_desc': '100% delivery fee is your earning - not deducted',
          'example_text': 'Example: Customer pays \$50 -> Order: \$45 + Delivery: \$5 -> You keep \$5, Restaurant gets \$45 from your balance',
          'recent_transactions': 'Recent Transactions',
          'order_value': 'Order Value',
          'delivery_fee_label': 'Delivery Fee',
          'deducted_label': 'Deducted',
          'your_earning_plus': '+@amount',
          'orders_history_title': 'Orders History',
          'all_orders_filter': 'All Orders',
          'completed_filter': 'Completed',
          'cancelled_filter': 'Cancelled',
          'no_orders_found': 'No orders found',
          'order_total': 'Order Total',
          'cash_label': 'Cash',
          'online_label': 'Online',
          'all_time': 'All Time',
          'this_week': 'This Week',
          'this_month': 'This Month',
          'complete_breakdown': 'Complete Breakdown',
          'delivery_fee_earning': 'Delivery Fee (Your Earning)',
          'deducted_from_rest': 'Deducted from Restaurant Balance',
          'net_effect': 'Net Effect on Balance',
          'deduction_desc': 'Only the order value is deducted from your restaurant deposit.',

          // --- Settlement ---
          'settlement_required': 'Settlement Required',
          'deposit_instruction': 'Deposit collected funds to continue',
          'you_must_deposit': 'You must deposit',
          'select_payment_method': 'Select Payment Method',
          'cash_at_office': 'Cash at Office',
          'visit_office_desc': 'Visit the nearest office to deposit',
          'digital_transfer': 'Digital Transfer',
          'digital_transfer_desc': 'Transfer via mobile payment',
          'confirm_deposit_check': 'I confirm that I have completed the deposit payment',
          'important_notice': 'Important Notice',
          'false_confirmation_warning': 'Only confirm after you\'ve actually made the deposit. False confirmations may result in account suspension.',
          'confirm_deposit_btn': 'Confirm Deposit Completed',
          'unlock_account_msg': 'This will unlock your account for new orders',

          // --- Order Details & Process ---
          'order_details_title': 'Order Details',
          'order_progress': 'Order Progress',
          'restaurant_details': 'Restaurant Details',
          'customer_details': 'Customer Details',
          'subtotal': 'Subtotal',
          'tax_label': 'Tax (8%)',
          'total_amount': 'Total Amount',
          'payment_method': 'Payment Method',
          'cash_on_delivery': 'Cash on Delivery',
          'collect_from_customer': 'Collect from Customer',
          'collect_cash_msg': 'You need to collect @amount in cash from the customer before completing the delivery.',
          'order_timeline': 'Order Timeline',
          'order_placed': 'Order Placed',
          'driver_on_way': 'Driver On the Way',
          'step_assigned': 'Assigned',
          'on_the_way_status': 'On the Way',
          'step_picked_up': 'Picked Up',
          'in_progress': 'In Progress...',
          'required_badge': 'Required',
          'each': 'each',
          'order_details_note': 'Follow each step carefully. For cash orders, you must collect payment from the customer before marking as delivered.',
          'status_preparing': 'Preparing',
          'navigate_btn': 'Navigate to Restaurant',
          'order_items_label': 'Order Items',
          'total_items_label': 'Total Items',
          'items_unit': 'items',
          'note_label': 'Note',
          'step_accepted': 'Order Accepted',
          'step_preparing': 'Preparing Food',
          'step_ready': 'Ready for Pickup',
          'min_ago_unit': 'min ago',
          'min_remain_unit': 'min remaining',
          'location_unlock_hint': 'The "Arrived at Restaurant" button will unlock when you\'re near the pickup location.',
          'arrived_btn': 'Arrived at Restaurant',
          'pickup_confirm_title': 'Pick Up Confirmation',
          'pickup_confirm_sub': 'Confirm order pickup',
          'arrived_rest_status': 'Arrived at Restaurant',
          'confirm_to_continue': 'Confirm pickup to continue',
          'scan_qr_tab': 'Scan QR',
          'order_num_tab': 'Order Number',
          'enter_order_num_label': 'Enter Order Number',
          'ask_staff_hint': 'Ask the restaurant staff for the order number',
          'orders_to_pickup_label': 'Orders to Pick Up',
          'pickup_warning_text': 'Make sure all items are packed correctly before confirming pickup.',
          'confirm_pickup_btn': 'Confirm Pickup',
          'qr_position_hint': 'Position QR code within frame',
          'tap_confirm_hint': 'If the customer does not click confirm within 10 minutes, the order will be considered accepted automatically.',          'proof_delivery_title': 'Proof of Delivery',
          'complete_delivery_sub': 'Complete the delivery',
          'almost_done_title': 'Almost Done!',
          'confirm_details_sub': 'Confirm delivery details',
          'confirm_instruction_text': 'Make sure the delivery is complete and the customer is satisfied before confirming.',
          'confirm_delivery_btn': 'Confirm Delivery',
          'step_delivering': 'Delivering',
          'step_collect_cash': 'Collect Cash',
          'step_delivered': 'Delivered',

          // --- Notifications ---
          'notifications': 'Notifications',
          'unread_count': 'unread:',
          'mark_all_read': 'Mark all read',
          'notif_new_order_title': 'New Order Request',
          'notif_new_order_desc': 'You have a new delivery request from Pizza Palace',
          'notif_payment_title': 'Payment Received',
          'notif_payment_desc': 'Weekly earnings of \$847.50 deposited to your account',
          'notif_peak_title': 'Peak Hours Alert',
          'notif_peak_desc': 'Dinner rush starting soon. Go online to earn bonus!',
          'notif_delivery_done_title': 'Delivery Completed',
          'notif_delivery_done_desc': 'Order #45821 delivered successfully. Earned \$12.50',
          'notif_doc_expire_title': 'Document Expiring Soon',
          'notif_doc_expire_desc': 'Your vehicle insurance expires in 7 days. Please update.',
          'notif_time_2min': '2 min ago',
          'notif_time_1h': '1 hour ago',
          'notif_time_3h': '3 hours ago',
          'notif_time_5h': '5 hours ago',
          'notif_time_1d': '1 day ago',
          'load_older_notif': 'Load Older Notifications',

          // --- Status & Home ---
          'online': 'Online',
          'offline': 'Offline',
          'status_label': 'Status',
          'online_msg': "You're Online",
          'go_online_msg': 'Go Online',
          'earnings_today': 'Earnings Today',
          'orders_today': 'Orders Today',
          'waiting_orders': 'Waiting for Orders...',
          'ready_accept_msg': 'Ready to accept orders',
          'offline_guidance_msg': 'Go online to start accepting\ndelivery orders',
          'app_name': 'NUMNOW',
          'courier': 'Courier',
          'welcome': 'Welcome back',
          'login': 'Login',
          'signup': 'Sign Up',
          'phone': 'Phone Number',
          'pass': 'Password',
          'forgot': 'Forgot Password?',
          'start': 'Start earning with us',
          'phone_hint': '05xxxxxxxx',
          'pass_hint': 'Enter your password',

          // --- Profile & Docs ---
          'personal_info': 'Personal Information',
          'profile_pic': 'Profile Picture',
          'full_name': 'Full Name',
          'full_name_hint': 'Enter your full name',
          'email': 'Email Address',
          'email_hint': 'example@mail.com',
          'vehicle_info': 'Vehicle Information',
          'vehicle_type': 'Vehicle Type',
          'select_vehicle': 'Select vehicle type',
          'bike': 'Bike',
          'car': 'Car',
          'truck': 'Truck',
          'plate_num': 'Plate Number',
          'city_zone': 'City / Zone',
          'select_city': 'Select city',
          'upload_docs': 'Upload Documents',
          'id_card': 'ID Card',
          'upload_id': 'Upload ID Card',
          'id_selected': 'ID Card Selected',
          'license': 'Driving License',
          'upload_license': 'Upload License',
          'license_selected': 'License Selected',
          'vehicle_reg': 'Vehicle Registration',
          'upload_reg': 'Upload Registration',
          'reg_selected': 'Registration Selected',
          'file_format_note': 'PNG, JPG (Max 5MB)',
          'note': 'Note',
          'admin_review_msg': 'Your account will be reviewed by the admin before activation.',
          'motorcycle': 'Motorcycle',
          'bicycle': 'Bicycle',
          'otp_title': 'Verification Code',
          'otp_subtitle': 'We have sent a verification code to',
          'otp_error_msg': 'Please enter the complete code',
          'verify_btn': 'Verify Now',
          'resend_code': 'Resend Code',
          'back_to_login': 'Back to Login',
          'forgot_pass_title': 'Forgot Password?',
          'forgot_pass_subtitle': "No worries! Enter your email address and we'll send you a link to reset your password.",
          'email_label': 'Email Address',
          'send_link_btn': 'Send Reset Link',
          'spam_folder_note': "Check your spam folder if you don't receive the email within a few minutes.",
          'check_email_title': 'Check Your Email!',
          'check_email_subtitle': "We've sent a password reset link to:",
          'next_steps_title': 'Next Steps',
          'step_1': 'Check your email inbox for a message from NUMNOW',
          'step_2': 'Click the reset link in the email (valid for 1 hour)',
          'step_3': 'Create a new password and login to your account',
          'didnt_receive_email': "Didn't receive the email?",
          'try_again_btn': 'Try Again',
          'under_review_title': 'Account Under Review',
          'under_review_subtitle': "We're reviewing your documents. This usually takes 24-48 hours.",
          'document_status': 'Document Status',
          'upload_missing_btn': 'Upload Missing Documents',
          'tips_label': 'Tips',
          'tips_desc': 'Make sure all documents are clear and valid. Once approved, you can start accepting deliveries immediately.',
          'continue_demo': 'Continue (Demo)',

          // --- Settings ---
          'settings_title': 'Settings',
          'manage_account_sub': 'Manage your account',
          'account_section': 'ACCOUNT',
          'profile_label': 'Profile',
          'phone_label': 'Phone',
          'vehicle_label': 'Vehicle',
          'security_section': 'SECURITY',
          'change_password_label': 'Change Password',
          'update_pass_sub': 'Update your password',
          'documents_section': 'DOCUMENTS',
          'verification_label': 'Verification Status',
          'verified_status': 'Verified',
          'preferences_section': 'PREFERENCES',
          'language_label': 'Language',
          'current_lang': 'English',
          'support_section': 'SUPPORT',
          'help_center_label': 'Help Center',
          'logout_btn': 'Logout',
          'rating_label': 'Rating',
          'deliveries_label': 'Deliveries',
          'active_status': 'Active Driver',
          'verified_status_badge': 'Verified Account',
          'privacy_settings_label': 'Privacy Settings',
          'control_data_sub': 'Control your data',
          'share_location_label': 'Share Location',
          'share_location_sub': 'Allow real-time location sharing',
          'show_rating_label': 'Show Rating',
          'show_rating_sub': 'Display your rating publicly',
          'language_sub': 'Select your preferred language',
          'current_pass_label': 'Current Password',
          'new_pass_label': 'New Password',
          'confirm_pass_label': 'Confirm New Password',
          'passwords_not_match': 'Passwords do not match',
          'edit_profile_title': 'Edit Profile',
          'full_name_label': 'Full Name',
          'valid_name': 'Valid name',
          'edit_phone_title': 'Edit Phone',
          'phone_num_label': 'Phone Number',
          'valid_phone': 'Valid phone number',
          'edit_email_title': 'Edit Email',
          'email_addr_label': 'Email Address',
          'valid_email': 'Valid email address',
          'edit_vehicle_title': 'Edit Vehicle',
          'vehicle_info_label': 'Vehicle Information',
          'valid_vehicle': 'Valid vehicle info',

          // --- Map Screen ---
          'delivering_sub': 'Delivering to customer',
          'in_transit_badge': 'In Transit',
          'marker_you': 'You',
          'marker_customer': 'Customer',
          'est_arrival_label': 'Est. Arrival',
          'distance_label': 'Distance',
          'call_btn': 'Call',
          'message_btn': 'Message',
          'note_title': 'Delivery Note:',
          'note_content': "Please leave at the door and ring the bell. Don't knock - baby sleeping.",
          'no_note': 'No notes provided',

          // --- New Order Request ---
          'busy_status_msg': 'You won\'t receive other requests while this is active',
          'respond_in': 'RESPOND IN',
          'new_order_req': 'New Order Request',
          'dist_to_rest': 'Dist. to Restaurant',
          'min_unit': 'min',
          'prep_time': 'Prep. Time',
          'deliv_dist': 'Delivery Dist.',
          'your_earning': 'Your Earning',
          'est_total_time': 'Est. Total Time',
          'decline_btn': 'Decline',
          'accept_btn': 'Accept',

          'blocked_account_title': 'Account Blocked',
          'blocked_account_subtitle': 'Your account has been suspended',
          'blocked_account_desc': 'Your account has been blocked by the administration. If you believe this is a mistake, please contact support.',
          'contact_support_btn': 'Contact Support',

          'navigate_customer_btn': 'Navigate to Customer',
          'arrived_customer_btn': 'Arrived at Customer',
        },
        'ar': {
          // --- عام ---
          'error': 'خطأ',
          'success_snack_title': 'نجاح',
          'success_snack_msg': 'تمت العملية بنجاح!',
          'cancel_btn': 'إلغاء',
          'save_btn': 'حفظ',
          'done_btn': 'تم',

          // --- المحفظة والمالية ---
          'wallet_title': 'المحفظة',
          'financial_overview': 'نظرة عامة مالية',
          'total_collected_today': 'إجمالي المحصل اليوم',
          'from_cash_orders': 'من @count طلبات نقدية',
          'to_be_deposited': 'المبلغ المطلوب إيداعه',
          'exceeded_threshold_msg': 'لقد تجاوزت حد الإيداع المسموح به. يرجى تسوية حسابك للمتابعة في استقبال الطلبات.',
          'limit_label': 'الحد الأقصى: @limit',
          'remaining_label': 'المتبقي: @amount',
          'your_earnings_label': 'أرباحك (رسوم التوصيل)',
          'earnings_msg': 'هذا هو صافي دخلك من رسوم التوصيل. متاح للسحب في أي وقت.',
          'cash_held_label': 'النقد المحتجز للتسوية',
          'cash_disclaimer': 'هذا هو النقد المحصل من العملاء - وليس أرباحك. يجب تسوية هذا المبلغ مع المنصة.',
          'view_cash_collections': 'عرض التحصيلات النقدية',
          'view_transactions': 'عرض المعاملات',
          'complete_history': 'السجل الكامل',
          'settle_balance': 'تسوية الرصيد',
          'process_deposit': 'إجراء الإيداع',
          'settle_now_btn': 'سدد الآن • @amount',
          'cash_collection_title': 'التحصيل النقدي',
          'financial_transactions': 'المعاملات المالية',
          'total_collected': 'إجمالي المحصل',
          'pending_settlement': 'تسوية معلقة',
          'not_included_earning': 'لم تدرج في أرباحك بعد',
          'all_filter': 'الكل',
          'pending_filter': 'معلق',
          'settled_filter': 'تمت التسوية',
          'disputed_filter': 'متنازع عليه',
          'order_col': 'الطلب',
          'amount_col': 'المبلغ',
          'status_col': 'الحالة',
          'settlement_col': 'التسوية',
          'financial_transactions_title': 'المعاملات المالية',
          'complete_history_desc': 'سجل مالي كامل',
          'current_balance': 'الرصيد الحالي',
          'available_withdrawal': 'متاح للسحب',
          'restaurant_held_balance': 'رصيد محتجز للمطعم',
          'security_deposit_msg': 'تأمين محتجز من قبل المطاعم للطلبات النقدية لضمان أمن الدفع.',
          'total_earnings': 'إجمالي الأرباح',
          'orders_count': '@count طلبات',
          'weekly_growth': '+@percent% هذا الأسبوع',
          'how_cash_work': 'كيفية عمل الطلبات النقدية',
          'understanding_flow': 'فهم آلية تدفق المدفوعات',
          'step_1_title': 'الزبون يدفع نقداً',
          'step_1_desc': 'أنت تحصل المبلغ كاملاً (الطلب + رسوم التوصيل)',
          'step_2_title': 'خصم قيمة الطلب',
          'step_2_desc': 'يتم خصم سعر الوجبة فقط من رصيد المطعم',
          'step_3_title': 'رسوم التوصيل لك',
          'step_3_desc': 'رسوم التوصيل 100% هي ربحك - لا يتم خصمها',
          'example_text': 'مثال: الزبون يدفع 50\$ -> الطلب: 45\$ + التوصيل: 5\$ -> أنت تحتفظ بـ 5\$، والمطعم يحصل على 45\$ من رصيدك',
          'recent_transactions': 'المعاملات الأخيرة',
          'order_value': 'قيمة الطلب',
          'delivery_fee_label': 'رسوم التوصيل',
          'deducted_label': 'المخصوم',
          'your_earning_plus': '+@amount',
          'orders_history_title': 'سجل الطلبات',
          'all_orders_filter': 'كل الطلبات',
          'completed_filter': 'المكتملة',
          'cancelled_filter': 'الملغية',
          'no_orders_found': 'لا توجد طلبات',
          'order_total': 'إجمالي الطلب',
          'cash_label': 'نقدي',
          'online_label': 'أونلاين',
          'all_time': 'كل الوقت',
          'this_week': 'هذا الأسبوع',
          'this_month': 'هذا الشهر',
          'complete_breakdown': 'تفصيل كامل للحساب',
          'delivery_fee_earning': 'رسوم التوصيل (ربحك)',
          'deducted_from_rest': 'مخصوم من رصيد المطعم',
          'net_effect': 'التأثير الصافي على الرصيد',
          'deduction_desc': 'يتم خصم قيمة الطلب فقط من تأمين المطعم الخاص بك.',

          // --- شاشة التسوية ---
          'settlement_required': 'مطلوب إجراء تسوية',
          'deposit_instruction': 'قم بإيداع المبالغ المحصلة للمتابعة',
          'you_must_deposit': 'يجب عليك إيداع مبلغ',
          'select_payment_method': 'اختر طريقة الدفع',
          'cash_at_office': 'نقداً في المكتب',
          'visit_office_desc': 'قم بزيارة أقرب مكتب للإيداع',
          'digital_transfer': 'تحويل رقمي',
          'digital_transfer_desc': 'التحويل عبر الهاتف المحمول',
          'confirm_deposit_check': 'أؤكد أنني قمت بإتمام عملية الإيداع',
          'important_notice': 'تنبيه هام',
          'false_confirmation_warning': 'لا تقم بالتأكيد إلا بعد قيامك بالإيداع فعلياً. التأكيدات غير الصحيحة قد تؤدي لإيقاف الحساب.',
          'confirm_deposit_btn': 'تأكيد إتمام الإيداع',
          'unlock_account_msg': 'هذا سيؤدي لفتح حسابك لاستلام طلبات جديدة',

          // --- تفاصيل الطلب ---
          'order_details_title': 'تفاصيل الطلب',
          'order_progress': 'تقدم الطلب',
          'restaurant_details': 'تفاصيل المطعم',
          'customer_details': 'تفاصيل العميل',
          'subtotal': 'المجموع الفرعي',
          'tax_label': 'الضريبة (8%)',
          'total_amount': 'المبلغ الإجمالي',
          'payment_method': 'طريقة الدفع',
          'cash_on_delivery': 'الدفع عند الاستلام',
          'collect_from_customer': 'التحصيل من العميل',
          'collect_cash_msg': 'يجب عليك تحصيل مبلغ @amount نقداً من العميل قبل إتمام عملية التوصيل.',
          'order_timeline': 'الجدول الزمني للطلب',
          'order_placed': 'تم تقديم الطلب',
          'driver_on_way': 'السائق في الطريق',
          'step_assigned': 'تم التعيين',
          'on_the_way_status': 'في الطريق',
          'step_picked_up': 'تم الاستلام',
          'in_progress': 'جاري العمل...',
          'required_badge': 'مطلوب',
          'each': 'للقطعة',
          'order_details_note': 'اتبع كل خطوة بعناية. بالنسبة للطلبات النقدية، يجب عليك تحصيل الدفع من العميل قبل وضع علامة تم التوصيل.',
          'status_preparing': 'قيد التحضير',
          'navigate_btn': 'التوجه للمطعم',
          'order_items_label': 'أصناف الطلب',
          'total_items_label': 'إجمالي الأصناف',
          'items_unit': 'أصناف',
          'note_label': 'ملاحظة',
          'step_accepted': 'تم قبول الطلب',
          'step_preparing': 'جاري التحضير',
          'step_ready': 'جاهز للاستلام',
          'min_ago_unit': 'دقيقة مضت',
          'min_remain_unit': 'دقيقة متبقية',
          'location_unlock_hint': 'سيتم تفعيل زر "وصلت للمطعم" عندما تكون قريباً من موقع الاستلام.',
          'arrived_btn': 'وصلت للمطعم',
          'pickup_confirm_title': 'تأكيد الاستلام',
          'pickup_confirm_sub': 'تأكيد استلام الطلب',
          'arrived_rest_status': 'وصلت للمطعم',
          'confirm_to_continue': 'أكد الاستلام للمتابعة',
          'scan_qr_tab': 'مسح QR',
          'order_num_tab': 'رقم الطلب',
          'enter_order_num_label': 'أدخل رقم الطلب',
          'ask_staff_hint': 'اطلب من موظف المطعم تزويدك برقم الطلب',
          'orders_to_pickup_label': 'طلبات للاستلام',
          'pickup_warning_text': 'تأكد من تغليف جميع الأصناف بشكل صحيح قبل تأكيد الاستلام.',
          'confirm_pickup_btn': 'تأكيد الاستلام',
          'qr_position_hint': 'ضع رمز QR داخل الإطار',
          'tap_confirm_hint': 'في حال لم يتم الضغط على تأكيد من قبل الزبون خلال عشر دقائق، سيتم اعتبار الطلب مقبولاً تلقائياً.',
          'proof_delivery_title': 'إثبات التوصيل',
          'complete_delivery_sub': 'إتمام عملية التوصيل',
          'almost_done_title': 'على وشك الانتهاء!',
          'confirm_details_sub': 'تأكيد تفاصيل التوصيل',
          'confirm_instruction_text': 'تأكد من إتمام عملية التوصيل ورضا العميل قبل التأكيد النهائي.',
          'confirm_delivery_btn': 'تأكيد التوصيل',
          'step_delivering': 'جاري التوصيل',
          'step_collect_cash': 'تحصيل المبلغ',
          'step_delivered': 'تم التوصيل',

          // --- الإشعارات ---
          'notifications': 'الإشعارات',
          'unread_count': 'غير مقروء:',
          'mark_all_read': 'تحديد الكل كمقروء',
          'notif_new_order_title': 'طلب جديد',
          'notif_new_order_desc': 'لديك طلب توصيل جديد من بيتزا بالاس',
          'notif_payment_title': 'تم استلام الدفعة',
          'notif_payment_desc': 'تم إيداع أرباحك الأسبوعية في حسابك',
          'notif_peak_title': 'تنبيه ساعات الذروة',
          'notif_peak_desc': 'ستبدأ ذروة العشاء قريباً. اتصل الآن لربح مكافأة!',
          'notif_delivery_done_title': 'تم التوصيل بنجاح',
          'notif_delivery_done_desc': 'تم توصيل الطلب بنجاح. ربحت \$12.50',
          'notif_doc_expire_title': 'اقتراب انتهاء الوثائق',
          'notif_doc_expire_desc': 'ينتهي تأمين مركبتك خلال 7 أيام. يرجى التحديث.',
          'notif_time_2min': 'منذ دقيقتين',
          'notif_time_1h': 'منذ ساعة',
          'notif_time_3h': 'منذ 3 ساعات',
          'notif_time_5h': 'منذ 5 ساعات',
          'notif_time_1d': 'منذ يوم',
          'load_older_notif': 'تحميل الإشعارات الأقدم',

          // --- الحالة والرئيسية ---
          'online': 'متصل',
          'offline': 'غير متصل',
          'status_label': 'الحالة',
          'online_msg': 'أنت متصل الآن',
          'go_online_msg': 'اتصل الآن',
          'earnings_today': 'أرباح اليوم',
          'orders_today': 'طلبات اليوم',
          'waiting_orders': 'بانتظار الطلبات...',
          'ready_accept_msg': 'جاهز لاستلام الطلبات',
          'offline_guidance_msg': 'اتصل بالإنترنت لبدء استلام طلبات التوصيل',
          'app_name': 'نوم ناو',
          'courier': 'مندوب التوصيل',
          'welcome': 'مرحباً بك مجدداً',
          'login': 'تسجيل الدخول',
          'signup': 'إنشاء حساب',
          'phone': 'رقم الهاتف',
          'pass': 'كلمة المرور',
          'forgot': 'نسيت كلمة المرور؟',
          'start': 'ابدأ الربح معنا',
          'phone_hint': '05xxxxxxxx',
          'pass_hint': 'أدخل كلمة المرور',

          // --- الملف الشخصي والتوثيق ---
          'personal_info': 'المعلومات الشخصية',
          'profile_pic': 'الصورة الشخصية',
          'full_name': 'الاسم الكامل',
          'full_name_hint': 'أدخل اسمك الرباعي',
          'email': 'البريد الإلكتروني',
          'email_hint': 'example@mail.com',
          'vehicle_info': 'معلومات المركبة',
          'vehicle_type': 'نوع المركبة',
          'select_vehicle': 'اختر نوع المركبة',
          'bike': 'دراجة نارية',
          'car': 'سيارة',
          'truck': 'شاحنة',
          'plate_num': 'رقم اللوحة',
          'city_zone': 'المدينة / النطاق',
          'select_city': 'اختر المدينة',
          'upload_docs': 'رفع المستندات',
          'id_card': 'الهوية الوطنية / الإقامة',
          'upload_id': 'ارفع صورة الهوية',
          'id_selected': 'تم اختيار الهوية',
          'license': 'رخصة القيادة',
          'upload_license': 'ارفع صورة الرخصة',
          'license_selected': 'تم اختيار الرخصة',
          'vehicle_reg': 'استمارة المركبة',
          'upload_reg': 'ارفع الاستمارة',
          'reg_selected': 'تم اختيار الاستمارة',
          'file_format_note': 'PNG, JPG (الحد الأقصى 5 ميجا)',
          'note': 'ملاحظة',
          'admin_review_msg': 'سيتم مراجعة حسابك من قبل الإدارة قبل التفعيل.',
          'motorcycle': 'دراجة نارية',
          'bicycle': 'دراجة هوائية',
          'otp_title': 'رمز التحقق',
          'otp_subtitle': 'لقد أرسلنا رمز التحقق إلى',
          'otp_error_msg': 'يرجى إدخال الرمز كاملاً',
          'verify_btn': 'تحقق الآن',
          'resend_code': 'إعادة إرسال الرمز',
          'back_to_login': 'العودة لتسجيل الدخول',
          'forgot_pass_title': 'نسيت كلمة السر؟',
          'forgot_pass_subtitle': 'لا تقلق! أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة التعيين.',
          'email_label': 'البريد الإلكتروني',
          'send_link_btn': 'إرسال رابط الاستعادة',
          'spam_folder_note': 'يرجى مراجعة ملف الرسائل المزعجة إذا لم يصلك البريد.',
          'check_email_title': 'تحقق من بريدك!',
          'check_email_subtitle': 'لقد أرسلنا رابط إعادة التعيين إلى:',
          'next_steps_title': 'الخطوات القادمة',
          'step_1': 'تحقق من صندوق الوارد الخاص بك',
          'step_2': 'انقر فوق رابط إعادة التعيين (صالح لساعة)',
          'step_3': 'أنشئ كلمة مرور جديدة وسجل الدخول',
          'didnt_receive_email': 'لم يصلك البريد الإلكتروني؟',
          'try_again_btn': 'حاول مرة أخرى',
          'under_review_title': 'الحساب قيد المراجعة',
          'under_review_subtitle': 'نحن نقوم بمراجعة مستنداتك حالياً. تستغرق العملية عادةً 24-48 ساعة.',
          'document_status': 'حالة المستندات',
          'upload_missing_btn': 'رفع المستندات الناقصة',
          'tips_label': 'نصيحة',
          'tips_desc': 'تأكد من أن جميع المستندات واضحة وسارية. بمجرد الموافقة، يمكنك البدء فوراً.',
          'continue_demo': 'متابعة (نسخة تجريبية)',

          // --- الإعدادات ---
          'settings_title': 'الإعدادات',
          'manage_account_sub': 'إدارة حسابك',
          'account_section': 'الحساب',
          'profile_label': 'الملف الشخصي',
          'phone_label': 'الهاتف',
          'email_label': 'البريد الإلكتروني',
          'vehicle_label': 'المركبة',
          'security_section': 'الأمان',
          'change_password_label': 'تغيير كلمة المرور',
          'update_pass_sub': 'تحديث كلمة المرور الخاصة بك',
          'documents_section': 'المستندات',
          'verification_label': 'حالة التحقق',
          'verified_status': 'تم التحقق',
          'preferences_section': 'التفضيلات',
          'language_label': 'اللغة',
          'current_lang': 'العربية',
          'support_section': 'الدعم',
          'help_center_label': 'مركز المساعدة',
          'logout_btn': 'تسجيل الخروج',
          'rating_label': 'التقييم',
          'deliveries_label': 'الطلبات',
          'active_status': 'سائق نشط',
          'verified_status_badge': 'حساب موثق',
          'privacy_settings_label': 'إعدادات الخصوصية',
          'control_data_sub': 'التحكم في بياناتك',
          'share_location_label': 'مشاركة الموقع',
          'share_location_sub': 'السماح بمشاركة الموقع في الوقت الفعلي',
          'show_rating_label': 'إظهار التقييم',
          'show_rating_sub': 'عرض تقييمك علناً',
          'language_sub': 'اختر لغتك المفضلة',
          'current_pass_label': 'كلمة المرور الحالية',
          'new_pass_label': 'كلمة المرور الجديدة',
          'confirm_pass_label': 'تأكيد كلمة المرور الجديدة',
          'passwords_not_match': 'كلمات المرور غير متطابقة',
          'edit_profile_title': 'تعديل الملف الشخصي',
          'full_name_label': 'الاسم الكامل',
          'valid_name': 'اسم صالح',
          'edit_phone_title': 'تعديل الهاتف',
          'phone_num_label': 'رقم الهاتف',
          'valid_phone': 'رقم هاتف صالح',
          'edit_email_title': 'تعديل البريد الإلكتروني',
          'email_addr_label': 'البريد الإلكتروني',
          'valid_email': 'بريد إلكتروني صالح',
          'edit_vehicle_title': 'تعديل المركبة',
          'vehicle_info_label': 'معلومات المركبة',
          'valid_vehicle': 'معلومات مركبة صالحة',

          // --- الخريطة ---
          'on_the_way_status': 'في الطريق',
          'delivering_sub': 'جاري التوصيل للعميل',
          'in_transit_badge': 'قيد الانتقال',
          'marker_you': 'أنت',
          'marker_customer': 'العميل',
          'est_arrival_label': 'الوصول المتوقع',
          'distance_label': 'المسافة',
          'call_btn': 'اتصال',
          'message_btn': 'رسالة',
          'note_title': 'ملاحظة التوصيل:',
          'note_content': 'يرجى ترك الطلب عند الباب ودق الجرس. الطفل نائم.',
          'no_note': 'لا توجد ملاحظات',

          // --- طلب جديد ---
          'busy_status_msg': 'لن تستلم طلبات أخرى أثناء نشاط هذا الطلب',
          'respond_in': 'الرد خلال',
          'new_order_req': 'طلب توصيل جديد',
          'dist_to_rest': 'المسافة للمطعم',
          'min_unit': 'دقيقة',
          'prep_time': 'وقت التحضير',
          'deliv_dist': 'مسافة التوصيل',
          'your_earning': 'ربحك المتوقع',
          'est_total_time': 'إجمالي الوقت المتوقع',
          'decline_btn': 'رفض',
          'accept_btn': 'قبول',

          'blocked_account_title': 'الحساب محظور',
          'blocked_account_subtitle': 'تم إيقاف حسابك من قبل الإدارة',
          'blocked_account_desc': 'لقد تم حظر حسابك من قبل الإدارة. إذا كنت تعتقد أن هذا حدث عن طريق الخطأ، يرجى التواصل مع الدعم الفني.',
          'contact_support_btn': 'تواصل مع الدعم',
          'navigate_customer_btn': 'التوجه للزبون',
          'arrived_customer_btn': 'وصلت للزبون',
        },
        'de': {
          'navigate_customer_btn': 'Zum Kunden navigieren',
          'arrived_customer_btn': 'Beim Kunden angekommen',
          'tap_confirm_hint': 'Wenn der Kunde nicht innerhalb von 10 Minuten auf Bestätigen klickt, gilt die Bestellung automatisch als angenommen.',
          'delivery_fee_earning': 'Liefergebühr (Ihr Verdienst)',
          'deducted_from_rest': 'Vom Restaurant-Guthaben abgezogen',
          'deducted_label': 'Abgezogen',
          'net_effect': 'Nettoeffekt auf das Guthaben',
          'step_1_desc': 'Sie kassieren den vollen Betrag (Bestellung + Liefergebühr)',
          'step_2_desc': 'Nur der Mahlzeitenpreis wird vom Restaurant-Guthaben abgezogen',
          'step_3_desc': '100% der Liefergebühr ist Ihr Verdienst - wird nicht abgezogen',
          'complete_breakdown': 'Vollständige Aufschlüsselung',
          'step_delivering': 'Wird geliefert',
          'step_delivered': 'Geliefert',
          'arrived_rest_status': 'Am Restaurant angekommen',
          'manage_account_sub': 'Konto verwalten',
          'account_section': 'KONTO',
          'profile_label': 'Profil',
          'phone_label': 'Telefon',
          'email_label': 'E-Mail',
          'vehicle_label': 'Fahrzeug',
          'security_section': 'SICHERHEIT',
          'change_password_label': 'Passwort ändern',
          'update_pass_sub': 'Passwort aktualisieren',
          'documents_section': 'DOKUMENTE',
          'verification_label': 'Verifizierungsstatus',
          'verified_status': 'Verifiziert',
          'preferences_section': 'EINSTELLUNGEN',
          'language_label': 'Sprache',
          'current_lang': 'Deutsch',
          'privacy_settings_label': 'Datenschutzeinstellungen',
          'control_data_sub': 'Daten kontrollieren',
          'share_location_label': 'Standort teilen',
          'share_location_sub': 'Echtzeit-Standortfreigabe erlauben',
          'show_rating_label': 'Bewertung anzeigen',
          'show_rating_sub': 'Bewertung öffentlich anzeigen',
          'language_sub': 'Wählen Sie Ihre bevorzugte Sprache',
          'current_pass_label': 'Aktuelles Passwort',
          'new_pass_label': 'Neues Passwort',
          'confirm_pass_label': 'Neues Passwort bestätigen',
          'passwords_not_match': 'Passwörter stimmen nicht überein',
          'edit_profile_title': 'Profil bearbeiten',
          'full_name_label': 'Vollständiger Name',
          'valid_name': 'Gültiger Name',
          'edit_phone_title': 'Telefon bearbeiten',
          'phone_num_label': 'Telefonnummer',
          'valid_phone': 'Gültige Telefonnummer',
          'edit_email_title': 'E-Mail bearbeiten',
          'email_addr_label': 'E-Mail-Adresse',
          'valid_email': 'Gültige E-Mail-Adresse',
          'edit_vehicle_title': 'Fahrzeug bearbeiten',
          'vehicle_info_label': 'Fahrzeuginformationen',
          'valid_vehicle': 'Gültige Fahrzeuginfos',
          'rating_label': 'Bewertung',
          'deliveries_label': 'Lieferungen',

          // --- عام ---
          'error': 'Fehler',
          'success_snack_title': 'Erfolg',
          'success_snack_msg': 'Vorgang erfolgreich abgeschlossen!',
          'cancel_btn': 'Abbrechen',
          'save_btn': 'Speichern',
          'done_btn': 'Fertig',

          // --- المحفظة والمالية ---
          'wallet_title': 'Brieftasche',
          'financial_overview': 'Finanzübersicht',
          'total_collected_today': 'Heute gesammelt',
          'from_cash_orders': 'Von @count Barbestellungen',
          'to_be_deposited': 'Einzوزاحلندر Betrag',
          'exceeded_threshold_msg': 'Limit überschritten. Bitte Konto ausgleichen.',
          'limit_label': 'Limit: @limit',
          'remaining_label': '@amount verbleibend',
          'your_earnings_label': 'Ihre Einnahmen',
          'earnings_msg': 'Nettoeinkommen aus Liefergebühren.',
          'cash_held_label': 'Bargeld zur Abrechnung',
          'cash_disclaimer': 'Gesammeltes Bargeld der Kunden - KEIN Verdienst.',
          'view_cash_collections': 'Barzahlungen anzeigen',
          'view_transactions': 'Transaktionen anzeigen',
          'complete_history': 'Verlauf',
          'settle_balance': 'Guthaben ausgleichen',
          'process_deposit': 'Einzahlung',
          'settle_now_btn': 'Jetzt abrechnen • @amount',
          'cash_collection_title': 'Bargeldsammlung',
          'financial_transactions': 'Finanztransaktionen',
          'total_collected': 'Gesamtsumme gesammelt',
          'pending_settlement': 'Ausstehend',
          'not_included_earning': 'Noch nicht in Einnahmen enthalten',
          'all_filter': 'Alle',
          'pending_filter': 'Ausstehend',
          'settled_filter': 'Abgerechnet',
          'disputed_filter': 'Umstritten',
          'order_col': 'BESTELLUNG',
          'amount_col': 'BETRAG',
          'status_col': 'STATUS',
          'settlement_col': 'ABRECHNUNG',
          'orders_history_title': 'Bestellverlauf',
          'all_orders_filter': 'Alle Bestellungen',
          'completed_filter': 'Abgeschlossen',
          'cancelled_filter': 'Storniert',
          'no_orders_found': 'Keine Bestellungen',
          'order_total': 'Bestellsumme',
          'cash_label': 'Barzahlung',
          'online_label': 'Online',
          'all_time': 'Gesamte Zeit',
          'this_week': 'Diese Woche',
          'this_month': 'Diesen Monat',

          // --- شاشة التسوية ---
          'settlement_required': 'Abrechnung erforderlich',
          'deposit_instruction': 'Geld hinterlegen zum Fortfahren',
          'you_must_deposit': 'Sie müssen einzahlen',
          'select_payment_method': 'Zahlungsmethode wählen',
          'cash_at_office': 'Barzahlung im Büro',
          'visit_office_desc': 'Nächstes Büro besuchen',
          'digital_transfer': 'Digitale Überweisung',
          'digital_transfer_desc': 'Mobile Zahlung',
          'confirm_deposit_check': 'Einzahlung bestätigt',
          'important_notice': 'Wichtiger Hinweis',
          'false_confirmation_warning': 'Falsche Bestätigungen führen zur Sperrung.',
          'confirm_deposit_btn': 'Einzahlung bestätigen',
          'unlock_account_msg': 'Schaltet Konto für neue Aufträge frei',

          // --- تفاصيل الطلب ---
          'order_details_title': 'Bestelldetails',
          'order_progress': 'Bestellfortschritt',
          'restaurant_details': 'Restaurant-Details',
          'customer_details': 'Kunden-Details',
          'subtotal': 'Zwischensumme',
          'tax_label': 'Steuer (8%)',
          'total_amount': 'Gesamtbetrag',
          'payment_method': 'Zahlungsmethode',
          'cash_on_delivery': 'Nachnahme',
          'collect_from_customer': 'Vom Kunden kassieren',
          'collect_cash_msg': 'Kassieren Sie @amount in bar.',
          'order_timeline': 'Bestellverlauf',
          'order_placed': 'Bestellung aufgegeben',
          'driver_on_way': 'Fahrer unterwegs',
          'step_assigned': 'Zugewiesen',
          'on_the_way_status': 'Unterwegs',
          'step_picked_up': 'Abgeholt',
          'in_progress': 'In Bearbeitung...',
          'required_badge': 'Erforderlich',
          'each': 'pro Stück',
          'order_details_note': 'Befolgen Sie jeden Schritt sorgfältig.',
          'status_preparing': 'Wird zubereitet',
          'navigate_btn': 'Navigieren',
          'order_items_label': 'Bestellte Artikel',
          'items_unit': 'Artikel',
          'note_label': 'Hinweis',
          'step_accepted': 'Angenommen',
          'step_preparing': 'Zubereitung',
          'step_ready': 'Bereit zur Abholung',
          'arrived_btn': 'Angekommen',
          'confirm_pickup_btn': 'Abholung bestätigen',
          'proof_delivery_title': 'Zustellnachweis',
          'complete_delivery_sub': 'Zustellung abschließen',
          'almost_done_title': 'Fast fertig!',
          'confirm_details_sub': 'Details bestätigen',
          'confirm_instruction_text': 'Stellen Sie sicher, dass Kunde zufrieden ist.',
          'confirm_delivery_btn': 'Lieferung bestätigen',

          // --- الإشعارات ---
          'notifications': 'Benachrichtigungen',
          'unread_count': 'ungelesen:',
          'mark_all_read': 'Alle gelesen',
          'notif_new_order_title': 'Neuer Auftrag',
          'notif_new_order_desc': 'Lieferanfrage von Pizza Palace',
          'notif_time_2min': 'Vor 2 Min.',
          'notif_time_1h': 'Vor 1 Std.',

          // --- الحالة والرئيسية ---
          'online': 'Online',
          'offline': 'Offline',
          'status_label': 'Status',
          'online_msg': 'Sie sind online',
          'go_online_msg': 'Online gehen',
          'earnings_today': 'Heutiger Verdienst',
          'orders_today': 'Heutige Bestellungen',
          'waiting_orders': 'Warten auf Bestellungen...',
          'ready_accept_msg': 'Bereit für Aufträge',
          'offline_guidance_msg': 'Gehen Sie online zum Starten',
          'app_name': 'NUMNOW',
          'courier': 'Kurier',
          'welcome': 'Willkommen zurück',
          'login': 'Anmelden',
          'signup': 'Registrieren',
          'phone': 'Telefon',
          'pass': 'Passwort',
          'forgot': 'Passwort vergessen?',
          'start': 'Verdienen Sie mit uns',

          // --- الملف الشخصي ---
          'personal_info': 'Persönliche Infos',
          'settings_title': 'Einstellungen',
          'logout_btn': 'Abmelden',
          'active_status': 'Aktiver Fahrer',
          'verified_status_badge': 'Verifiziertes Konto',

          // --- الخريطة ---
          'marker_you': 'Sie',
          'marker_customer': 'Kunde',
          'est_arrival_label': 'Ankunft ca.',
          'distance_label': 'Entfernung',
          'call_btn': 'Anrufen',
          'message_btn': 'Nachricht',
          'note_title': 'Hinweis:',

          // --- New Order Request ---
          'busy_status_msg': 'Sie erhalten keine weiteren Anfragen, während diese aktiv ist',
          'respond_in': 'ANTWORTEN IN',
          'new_order_req': 'Neue Bestellanfrage',
          'dist_to_rest': 'Entf. zum Restaurant',
          'min_unit': 'Min',
          'prep_time': 'Zubereitungszeit',
          'deliv_dist': 'Lieferentfernung',
          'your_earning': 'Ihr Verdienst',
          'est_total_time': 'Geschätzte Gesamtzeit',
          'decline_btn': 'Ablehnen',
          'accept_btn': 'Annehmen',

          'blocked_account_title': 'Konto gesperrt',
          'blocked_account_subtitle': 'Ihr Konto wurde deaktiviert',
          'blocked_account_desc': 'Ihr Konto wurde von der Verwaltung gesperrt. Bitte kontaktieren Sie den Support für weitere Informationen.',
          'contact_support_btn': 'Support kontaktieren',
        },
      };
}